language: java
jdk:
  - oraclejdk8
env:
  matrix:
    - ELASTICSEARCH_VERSION=7.2.0
    - ELASTICSEARCH_VERSION=7.1.1
    - ELASTICSEARCH_VERSION=7.1.0
    - ELASTICSEARCH_VERSION=7.0.1
    - ELASTICSEARCH_VERSION=7.0.0
    - ELASTICSEARCH_VERSION=6.8.0
    - ELASTICSEARCH_VERSION=6.7.2
    - ELASTICSEARCH_VERSION=6.7.1
    - ELASTICSEARCH_VERSION=6.7.0
    - ELASTICSEARCH_VERSION=6.6.2
    - ELASTICSEARCH_VERSION=6.6.1
    - ELASTICSEARCH_VERSION=6.6.0
    - ELASTICSEARCH_VERSION=6.5.4
    - ELASTICSEARCH_VERSION=6.5.3
    - ELASTICSEARCH_VERSION=6.5.2
    - ELASTICSEARCH_VERSION=6.5.1
    - ELASTICSEARCH_VERSION=6.5.0

script: "mvn clean install -Delasticsearch.version=${ELASTICSEARCH_VERSION}"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: target/releases/*.zip
  skip_cleanup: true
  on:
    tags: true