language: java
jdk:
  - oraclejdk8
env:
  matrix:
    - ELASTICSEARCH_VERSION=6.2.2
    - ELASTICSEARCH_VERSION=6.2.1
    - ELASTICSEARCH_VERSION=6.2.0
    - ELASTICSEARCH_VERSION=6.1.3
    - ELASTICSEARCH_VERSION=6.1.2
    - ELASTICSEARCH_VERSION=6.1.1
    - ELASTICSEARCH_VERSION=6.0.1
    - ELASTICSEARCH_VERSION=6.0.0

script: "mvn clean install -Delasticsearch.version=${ELASTICSEARCH_VERSION}"