language: java
jdk:
  - oraclejdk8
env:
  matrix:
    - ELASTICSEARCH_VERSION=6.2.4
    - ELASTICSEARCH_VERSION=6.2.3
    - ELASTICSEARCH_VERSION=6.2.2
    - ELASTICSEARCH_VERSION=6.2.1
    - ELASTICSEARCH_VERSION=6.2.0
    - ELASTICSEARCH_VERSION=6.1.3
    - ELASTICSEARCH_VERSION=6.1.2
    - ELASTICSEARCH_VERSION=6.1.1
    - ELASTICSEARCH_VERSION=6.0.1
    - ELASTICSEARCH_VERSION=6.0.0

script: "mvn clean install -Delasticsearch.version=${ELASTICSEARCH_VERSION}"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: target/releases/*.zip
  skip_cleanup: true
  on:
    tags: true